import "./globals.css";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montserratSans = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal"],
  display: "swap",
  variable: "--font-montserrat",
});
// оголошуються змінні для підключених шрифтів
// <body className={`${montserratSans.variable} antialiased`}> Додає змінні шрифтів

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserratSans.variable} antialiased`}>
        {/*className={`${montserratSans.variable} Додає змінні шрифтів у клас body*/}
        {/* antialiased покращує згладжування тексту*/}
        {children}
      </body>
    </html>
  );
}
